name: Elsie Grace Tomaszewski
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37615
title: Elsie Grace Tomaszewski
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00a600'
    - '#000900'
    - '#b00000'
    - '#ffffff'
    - '#7ab600'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
