name: ElsieTomaszewski
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37615
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00a600'
    - '#000900'
    - '#b00000'
    - '#ffffff'
    - '#7ab600'
  brandStrength: 0.2302506163250655
  lightness: 0.30638252780772746
  saturation: 0.5683352784253657
  rhythmicContrast: 0.15864346106536686
purpose: []
